### ISSUE TITLE
Make the value linear with 90deg at the bar

### ISSUE THREAD

**Issue by jourdanrodrigues** [hxf31891/react-gradient-color-picker#10]
This should happen [here](https://github.com/hxf31891/react-gradient-color-picker/blob/main/src/GradientBar.js#L30).

I fixed it on my side by having this Styled-Components selector: 

```css
.ps-rl.bar-wrap-inner > div:first-child > div:not([class='handle']) {
  background-image: ${({ color }) => force90degLinear(color)} !important;
}
``` 

And the `force90degLinear` function looks like this:

```js
function force90degLinear(color: string): string {
  return color.replace(
    /(radial|linear)-gradient\([^,]+,/,
    'linear-gradient(90deg,'
  );
}
```

| Before | After |
| - | - |
| ![image](https://user-images.githubusercontent.com/6227037/186757126-8cc28e35-3c73-42fd-b4aa-a2da554adb6d.png) | ![image](https://user-images.githubusercontent.com/6227037/186757206-13853685-01f4-4752-9663-daffd5dde685.png) |

**Comment by hxf31891** [comment]
Please create a PR and I'll merge it.

**Comment by hxf31891** [comment]
Added your function, I never noticed this behaviour and I like this fix a lot. Will be included in next version.
