### ISSUE TITLE
Add height prop

### ISSUE THREAD

**Issue by dmbarry86** [hxf31891/react-gradient-color-picker#11]
As a follow up to https://github.com/hxf31891/react-gradient-color-picker/issues/5#issuecomment-1227066317 where width prop was added, we discussed the requirement for a new height prop to achieve a design similar to that shown below. I've created this separate issue for height as the responsiveness task is now closed off.

![image](https://user-images.githubusercontent.com/8976377/187619082-e7395e44-f09a-4e32-9c39-b24ed3f1bc86.png)

**Comment by hxf31891** [comment]
Working on v2.0.14 to add height prop.

**Comment by hxf31891** [comment]
Would appreciate if you could take a minute and test this version 

`npm i react-best-gradient-color-picker@2.0.14-beta.0`

pass in `num` height

**Comment by dmbarry86** [comment]
Works perfectly. Thanks for implementing.

**Comment by dmbarry86** [comment]
I guess the console log during picker drag is just for debugging purposes and will be removed in the end release.

![image](https://user-images.githubusercontent.com/8976377/188093031-9aa68615-629c-4341-80c2-6ac115b8e12a.png)

**Comment by hxf31891** [comment]
Hahaha yea I noticed that as well. Launched the new feature under v2.0.14.

Keep the issues and bugs coming, I enjoy working on this project and hope to turn it into something pretty good.
