### ISSUE TITLE
multiple ColorPicker dom id conflicts

### ISSUE THREAD

**Issue by webyonet** [hxf31891/react-gradient-color-picker#114]
Hello, since you are using id in dom elements, when we use 2 color pickers at the same time, it causes conflicts in the dom.
e.g `id="rbgcp-wrapper"`

Dark and light modes work well when used with a single colorpicker. But when multiple color pickers are used, 2 different themes cannot be used.

```javascript
// instance 1 (dark)
<ColorPicker 
    disableLightMode={true}
    disableDarkMode={false} // Dark mode works fine
/>

// instance 2 (light)
<ColorPicker 
    disableLightMode={false} // Light mode not working
    disableDarkMode={true} 
/>
```

**Comment by hxf31891** [comment]
@webyonet fixed in v3.0.12
