### ISSUE TITLE
Enhancement suggestion, option to disable the square (x,y) color selector up top. 

### ISSUE THREAD

**Issue by RebZJ** [hxf31891/react-gradient-color-picker#115]
Hi, I was wondering if we could have an option to disable the square (x,y) color selector. It would be helpful for mobile usage where there's not that much space. Setting the height to 0 seems to make it disappear, however the selector is still visible. 

Oh and could we possible have a dragging option for the angle? 

Please consider and thank you, love your work.

**Comment by hxf31891** [comment]
@RebZJ this seems like an easy add, will take a look at adding ASAP.

**Comment by hxf31891** [comment]
@RebZJ added as "hidePickerSquare" in v3.0.12
