### ISSUE TITLE
Preview without borders

### ISSUE THREAD

**Issue by Qiu-Jun** [hxf31891/react-gradient-color-picker#117]
Repeat step：
1：Set solid mode
2：input red = 255, green 255, blue = 255

Bug cause:
 Because code spaces in  `p === 'rgba(255,255,255, 1)'` and `rgba(${newVal}, ${g}, ${b}, ${a})`  is different
![91d281c1439727aa2886468c95d944a](https://github.com/user-attachments/assets/74e5d351-3ac1-4c19-9155-3ecc9eb35d69)

**Comment by Qiu-Jun** [comment]
#118

**Comment by hxf31891** [comment]
@Qiu-Jun thank you for creating the PR, I will merge now
