### ISSUE TITLE
Enforce code style with ESLint

### ISSUE THREAD

**Issue by jourdanrodrigues** [hxf31891/react-gradient-color-picker#15]
I'm the second one hopping into this project, and I doubt will be the last one.

Ensuring this lib enforces an agreed code style that everyone joining in has to follow can really avoid annoying nitpicks down the road.

**Comment by jourdanrodrigues** [comment]
These are some of the style guides that we can pick. Feels like Standard is very close to the existing code base, and can be tweaked along the way.

![image](https://user-images.githubusercontent.com/6227037/188635050-48e8c13e-ee74-414c-829b-63b73256df86.png)

**Comment by hxf31891** [comment]
Standard works great for me, however I haven't  implemented anything like this in the past. Do you know the process?

**Comment by jourdanrodrigues** [comment]
@hxf31891 Yep, I'll send a PR shortly.
