### ISSUE TITLE
Issue with default styling and focus loss

### ISSUE THREAD

**Issue by vercamach** [hxf31891/react-gradient-color-picker#17]
Hello,

I'm not sure if I'm missing something but I have some issues to get the color picker look like in the demo. From what I can see I have to add `line-height: 1.5` to the wrapper, and `*, :after, :before {box-sizing: border-box;} `. Adding the line height is simple, adding the box-sizing however is breaking styling in the application on multiple places. 

Are there some plans to include the default styling in the package itself or is there some other way how to achieve the styling to look as expected :) ?

![Screenshot 2022-09-05 at 15 47 41](https://user-images.githubusercontent.com/26543699/188556394-61769fd6-80c0-462c-bb38-8e204e872a23.png)

Another issue I encountered is that when I'm dragging the color selector the moment the cursor is not within the window it looses focus. 

https://user-images.githubusercontent.com/26543699/188558732-d375584c-a033-45d7-829c-0ce9b19da120.mov

**Comment by hxf31891** [comment]
@vercamach could you tell me what version you are using? 

It is meant to ship with the default sizing, but we recently updated the way the picker is styled to make compiling on Next and other non ES6 frameworks easier. I am guessing that some of the styling was lost in the process.

Thanks for bringing this to my attention.

**Comment by pawelkontek** [comment]
@hxf31891 I have the same issue with losing focus on v2.1.13. Do you think you will find a solution?

**Comment by hxf31891** [comment]
Hi @pawelkontek, I believe I had a fix for this issue at one point a while ago but it seems like a slipped through the cracks. I will take a peak at getting this fixed up as soon as time allows.

**Comment by hxf31891** [comment]
@pawelkontek @sytolk @vercamach  focus issue is resolved in v2.1.18. 

I believe that the styling issues are also resolved so I am going to close this issue, but please feel free to open a new one if any issues remain or new bugs arise.
