### ISSUE TITLE
Bug in percentage selector for gradient when custom width is specified

### ISSUE THREAD

**Issue by vercamach** [hxf31891/react-gradient-color-picker#20]
Hello,

If the width prop is given a value and the gradient type is used, the gradient percentage (not sure how to call it) selector is having wrong position when being dragged.

https://codesandbox.io/s/fragrant-morning-huitsf?file=/src/App.js

https://user-images.githubusercontent.com/26543699/188808279-10e09fdc-a035-4609-8fe8-bcd2dda3d16c.mov

**Comment by hxf31891** [comment]
Interesting, will check this out ASAP

**Comment by hxf31891** [comment]
Fixed in version 2.0.20.

Thanks for bring this up, please feel free to bring forward anymore issues your having.
