### ISSUE TITLE
v2.0.17, useColorPicker is not a function

### ISSUE THREAD

**Issue by renzhiVivio** [hxf31891/react-gradient-color-picker#23]
![image](https://user-images.githubusercontent.com/23386884/191662294-578f5bb7-eaa7-4579-bebe-19e8719317cb.png)

All code from readme or https://gradient-package-demo.web.app/

**Comment by sytolk** [comment]
Hi, try to `import ColorPicker, { useColorPicker } from 'react-best-gradient-color-picker';`

**Comment by hxf31891** [comment]
Hi @renzhiVivio, I just pushed a fix for a different issue on the useColorPicker hook that I hope solves you problem. Please give version 2.0.19 a try. If the issue persists show me how your importing the function and we can go from there.

**Comment by hxf31891** [comment]
I am closing this as I believe it to be fixed with v2.0.19 but please feel free to reopen if the behavior is persisting.
