### ISSUE TITLE
Maximum update depth exceeded when using useColorPicker 

### ISSUE THREAD

**Issue by jpdery** [hxf31891/react-gradient-color-picker#24]
Hi,
I'm using version 2.0.17 with react 18.1.0 and as soon as I call useColorPicker, I get a maximum update depth error.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/572660/191757023-51efb84a-ed8b-44f6-b0f0-b05ecbaea94d.png">

Is there a way to fix this ?

Thanks

**Comment by BentleyDavis** [comment]
We are seeing this in both React 17 and 18. Here is a React 18 code Sandbox with just your demo code in it: We will need to go back to version 2.0.10

https://codesandbox.io/s/eloquent-cloud-oiq2hg

![image](https://user-images.githubusercontent.com/1606382/192012926-517a37c1-3f48-4c36-84b7-23ba163e32de.png)

**Comment by BentleyDavis** [comment]
I did a diff between v2.0.10 and v2.0.11 and I don't see anything obvious. There were a lot of changes to enable the new  width prop. It would take while learning the code and to debug it. I'm not sure I will have the time to dedicate to find it.

**Comment by hxf31891** [comment]
Thats no good, I will take a look tonight.

**Comment by hxf31891** [comment]
@BentleyDavis & @jpdery thanks for pointing this out, it seems to have slipped through the cracks. I'm not exactly sure what updates were breaking, or better said I'm not sure how that function ever worked, but it was any easy fix. See version 2.0.19.

Happy coding!
