### ISSUE TITLE
Module not found: Can't resolve 'react-best-gradient-color-picker' #27

### ISSUE THREAD

**Issue by Harshalyadav** [hxf31891/react-gradient-color-picker#27]
![Screenshoteror(5)](https://user-images.githubusercontent.com/54142355/194920784-ad38ba93-fde9-459c-96fc-5e7159a65468.png)

**Comment by hxf31891** [comment]
Can you upload a photo of your package.json please?

**Comment by Harshalyadav** [comment]
![ScreenshotRequest(6)](https://user-images.githubusercontent.com/54142355/195135288-88c7738b-d03f-4583-9247-c9d5b12f32fb.png)

yes, I do npm i react-best-gradient-color-picker.

**Comment by hxf31891** [comment]
I've been racking my head on this one and I havn't been able to make much progress or recreate the issue. Were you able to figure anything out?
