### ISSUE TITLE
selectedPoint and deletePoint no longer working in v=2.0.21

### ISSUE THREAD

**Issue by Refractive-Strategy** [hxf31891/react-gradient-color-picker#28]
It would seem that '`selectedPoint`' and '`deletePoint`' is no longer working in v=2.0.21

The '`selectedPoint`' only returns a 0 no matter which point is selected. And even when a 0 is passed into `deletePoint()` it returns an error saying "A gradient must have at least 2 colors, disable your delete button..." 
![image](https://user-images.githubusercontent.com/79570477/196288873-77d1c80b-7e8b-4c66-95fb-72b41ebd27e1.png)

--
The **trash-can** '**delete point**' that's part of the component's inherent controls still works though.

**Comment by hxf31891** [comment]
Hey @Refractive-Strategy, thank you for pointing this out. Would you please post a screenshot of your code, specifically where you initially declare the useColorPicker hook. i.e. `const { selectedPoint } = useCol...`

**Comment by Refractive-Strategy** [comment]
![image](https://user-images.githubusercontent.com/79570477/196483205-b95cc128-57f5-4af9-b28f-d7bf05ca7c08.png)
