### ISSUE TITLE
In demo app , eye dropper color picker isn't working properly

### ISSUE THREAD

**Issue by rishonide-swivel** [hxf31891/react-gradient-color-picker#29]

**Comment by Codigo-Fuentes** [comment]
not working in my app either

**Comment by hxf31891** [comment]
Yea I've noticed some wonky behavior on that component for a while now, I'm going to do a deep dive into it when I get a minute

**Comment by hxf31891** [comment]
I believe this to fixed in v2.1.5, but I've observed in the past that it preforms differently on various element types (svg, img etc). I have tested this newest version on most of the common elements but please reopen if you find the issue persisting somewhere.

Appreciate the help as always.
