### ISSUE TITLE
Removing color stops

### ISSUE THREAD

**Issue by schnubor** [hxf31891/react-gradient-color-picker#30]
Hi,

1st of all, thanks for making this lib :)

Not a bug, just a thing I noticed: I was playing around with the demo and noticed it's quite tedious to remove color stops (using the trash button). Would be great to just being able to use Backspace or even drag n drop the color stop out of the track so you don't require a button in your UI to remove them. Example: https://cssgradient.io/

I think using the delete/backspace key can be achieved using the hook somehow, but the drag n drop method seems more complicated I assume?

Anyway, just leaving this here and would love to see it. 

Thanks and keep it up :)

**Comment by hxf31891** [comment]
Interesting idea, I like it! I think we could roadmap some additional features in the same realm like switching between points with the tab button and so forth. Will spin a branch with keyboard listeners if your willing to do a little testing.

**Comment by schnubor** [comment]
Thanks! Absolutely :)

**Comment by hxf31891** [comment]
Added the described the functionality in version 2.1.6, also added the tab button to quickly switch between selected points.

Take a peak and let me know what you think!

**Comment by schnubor** [comment]
> Added the described the functionality in version 2.1.6, also added the tab button to quickly switch between selected points.
> 
> Take a peak and let me know what you think!

Hey, thanks for the quick implementation :) I can confirm that backspace removes the color stop and tabbing through the color stops works as well (cool!), but no matter how much I drag the color stop out of the track, it's not removed. I think that would be the most intuitive thing to do though in order to remove it.
