### ISSUE TITLE
why eyedropper does not support Firefox 

### ISSUE THREAD

**Issue by rishonide-swivel** [hxf31891/react-gradient-color-picker#31]
![Screenshot from 2022-10-28 08-32-51](https://user-images.githubusercontent.com/107900457/198487609-42e9883b-e634-42ce-969f-43499a13880e.png)

**Comment by hxf31891** [comment]
Please give me some more information, what is the behavior exactly? What version are you using?

**Comment by rishonide-swivel** [comment]
> Please give me some more information, what is the behavior exactly? What version are you using?

seems it doesn't support on firefox browser. color doesn't pick in firefox browser

**Comment by hxf31891** [comment]
What version of the color picker are you using?

**Comment by rishonide-swivel** [comment]
> What version of the color picker are you using?
"react-best-gradient-color-picker": "2.1.5", this works fine in chrome

**Comment by hxf31891** [comment]
The eye dropper works differently on different browsers. By far the best functionality is provided by the recently released  [EyeDropper API](https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper_API). Unfortunately, it still has very limited browser compatibility (Chrome, Opera & Edge). I implemented a custom Eye Dropper for all non compatible browsers. To my knowledge, that functionality is working as expected, although the component does look quite different. 

I'm testing on Firefox now and getting desired behavior. (see attached video).  I will confess however that I rarely use Firefox. If your experiencing some other bugs give me a detailed breakdown and I'll try and get it fixed up ASAP.

https://user-images.githubusercontent.com/49292623/198558648-f35e94b4-5a7b-4d22-80b9-6e547b1be246.mov

**Comment by rishonide-swivel** [comment]
> The eye dropper works differently on different browsers. By far the best functionality is provided by the recently released [EyeDropper API](https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper_API). Unfortunately, it still has very limited browser compatibility (Chrome, Opera & Edge). I implemented a custom Eye Dropper for all non compatible browsers. To my knowledge, that functionality is working as expected, although the component does look quite different.

could you let me know the version of firefox?

**Comment by hxf31891** [comment]
Firefox 106.0.2 on Mac Silicon

**Comment by hxf31891** [comment]
Closing with assumption package is functioning normally
