### ISSUE TITLE
Can't use delete key in other inputs on page

### ISSUE THREAD

**Issue by Codigo-Fuentes** [hxf31891/react-gradient-color-picker#33]
When color pickers are present and one of them is set to gradient mode, the delete key on other inputs in the page stops working. Moving all color pickers into their own component did not resolve the issue.

When i press 'delete' in another input under these conditions the onChange event doesn't fire. Entering new characters works fine.

**Comment by Codigo-Fuentes** [comment]
when i press 'delete' in another input under these conditions the onChange event doesn't fire

**Comment by hxf31891** [comment]
Fixed in V2.1.17

**Comment by Codigo-Fuentes** [comment]
@hxf31891 

In V2.1.7, pressing the delete key while in another input now correctly deletes text in that input but also now deletes gradient stops if there are more than 2.

**Comment by hxf31891** [comment]
Alright I'm going to do a little deeper dive into this, will update you soon.

**Comment by hxf31891** [comment]
Ok I feel like v2.1.9 is finally going to get solid behavior here. The gradient points now accept focus like an input does which should eliminate the bugs you've been describing which seem to stem from cross interaction between those two elements.

I've tested it pretty thoroughly but I would very much appreciate if you could detail any issues you find here. I am uncertain about the functionality specifically on Next so if thats part of your environment let me know how it looks.

**Comment by hxf31891** [comment]
Closing with assumption this is fixed in 2.1.9
