### ISSUE TITLE
Unreachable Colors in the UI 

### ISSUE THREAD

**Issue by RikTheGuy** [hxf31891/react-gradient-color-picker#34]
Since the edges of the picker are rounded, cursor cannot go to extreme points and never select values like #ffffff and #000000, they stop around #fafafa and #030303

**Comment by hxf31891** [comment]
@RikTheGuy v2.1.18 adjusts the picker areas min/max and should allow you to reach ALMOST all colors. The only area I am still having trouble with is the top left corner (255,255,255). I am going to close this, but will continue to try and improve the range.
