### ISSUE TITLE
Error with tinycolor library

### ISSUE THREAD

**Issue by mhuretski** [hxf31891/react-gradient-color-picker#39]
Hi, 

![image](https://user-images.githubusercontent.com/22213256/223481694-c491d765-5d08-4bc0-96a5-4a82fa94392d.png)

it has dependency `"tinycolor2": "^1.4.2"`and when pulled it's stored

```
tinycolor2@^1.4.2:
  version "1.6.0"
  resolved "https://registry.yarnpkg.com/tinycolor2/-/tinycolor2-1.6.0.tgz#f98007460169b0263b97072c5ae92484ce02d09e"
  integrity sha512-XPaBkWQJdsf3pLKJV9p4qN/S+fm2Oj8AIPo1BTUhg5oxkvm9+SVEGFdhyOz7tTdUTfvxMiAs4sp6/eZO2Ew+pw==

```
there is breaking change in 1.5.0 https://github.com/bgrins/TinyColor/issues/249

Could you update the dependency to `"tinycolor2": "1.4.2"` or fix it using updated library?

**Comment by hxf31891** [comment]
@mhuretski good find! Thank you for pointing this out, I will update ASAP.

**Comment by hxf31891** [comment]
Updated in version 2.1.13
