### ISSUE TITLE
Can't change hue when node selection is leftmost

### ISSUE THREAD

**Issue by BabyFriedCake** [hxf31891/react-gradient-color-picker#4]
Can't change hue when node selection is leftmost.
![WX20220601-104447](https://user-images.githubusercontent.com/33448924/171318545-ef9627b9-8d51-41a6-99b6-2a40373faea7.png)

**Comment by hxf31891** [comment]
Interesting, will look into this.

**Comment by BabyFriedCake** [comment]
> Interesting, will look into this.
At the bottom, there is also a problem with the hue sliding, and only six can be selected.
![image](https://user-images.githubusercontent.com/33448924/172321039-1160c9af-cb53-403a-b794-794584e0f0c6.png)

https://user-images.githubusercontent.com/33448924/172320785-f97ef42d-d1ab-46d3-a60e-50774f3a9041.mp4

**Comment by hxf31891** [comment]
I am aware of the second issue and believe the two to be related.

Testing a solution that I am hopeful will solve both and increase responsiveness of the hue slider which I've always found a bit jumpy.

**Comment by hxf31891** [comment]
@BabyFriedCake please see version 2.0.6

I believe this issue to be fixed and am closing this issue but please comment if I am incorrect or you find anything else.
