### ISSUE TITLE
"Tap-and-move" in a random place

### ISSUE THREAD

**Issue by ice-lenor** [hxf31891/react-gradient-color-picker#41]
Hello and thanks for a great project! This is not necessarily a bug, more of a feature request.

What works: when I want to move the color pointer on the canvas, I can grab the current circle and move it wherever I want, the circle follows the cursor. If I click on a random place, the circle moves to that place. All that works well.

What doesn't work: if I mouse down (or tap) on a random place and start moving, the circle doesn't follow the cursor (until I release the mouse on desktop and, it seems, never on mobile?..).

I hope it makes sense, I don't know how to better describe it. This is especially inconvenient on mobile, as my fingers are too thick to tap precisely on the circle )). On mobile only a single tap seems to work for me, dragging doesn't work at all.

Here is an example of a color picker (no gradient though!) that does what I am trying to describe: https://omgovich.github.io/react-colorful/.

Am I missing something? How do I make this work? Or is it something that needs to be fixed?

Thanks in advance!

**Comment by hxf31891** [comment]
@ice-lenor this functionality is now available in v2.1.18

**Comment by ice-lenor** [comment]
Fantastic, thank you very much @hxf31891
