### ISSUE TITLE
Hide Alpha Input

### ISSUE THREAD

**Issue by madisonc33** [hxf31891/react-gradient-color-picker#43]
When using hideOpacity, it hides the opacity slider, but users are still able to edit the alpha input. Would it make sense to hide alpha input with opacity? Or create a second option to hide alpha? For my use case, we don't want users to able to add alphas - just RBG.

**Comment by hxf31891** [comment]
@madisonc33 Nvm I threw together a quick fix. In version 2.1.17 hideOpacity should also remove the alpha input. Would appreciate if you can report any adverse behavior created here on this thread.
