### ISSUE TITLE
Support HEX color as initialize value

### ISSUE THREAD

**Issue by ngocducdim** [hxf31891/react-gradient-color-picker#46]
Hi, by default I pass the HEX color as initialize value, but look like it not accept the HEX color, the error said:
![image](https://github.com/hxf31891/react-gradient-color-picker/assets/97713182/9ea058bd-8f20-4664-bd4e-d6bb4eb21495)
is there anyway accept the HEX color as initialize value? Thanks

**Comment by hxf31891** [comment]
@ngocducdim interesting, I will look into this ASAP.

**Comment by hxf31891** [comment]
@ngocducdim can you please post an example of an initial hex value you are using?
