### ISSUE TITLE
Why select gradient point trigger onChange event ?

### ISSUE THREAD

**Issue by jianghai** [hxf31891/react-gradient-color-picker#47]
My Code
```ts
function MyApp() {
  const [color, setColor] = useState('linear-gradient(90deg, rgba(96,93,93,1) 0%, rgba(255,255,255,1) 100%)');

  return <ColorPicker value={color} onChange={setColor} />
}
```
My requirement is very simple, which is to get the color selected by the user. However, in the current design, the onChange event is triggered after the user selects a gradient point, but the user has not finished the selection yet. As a result, they are unable to continue selecting.

**Comment by hxf31891** [comment]
Unfortunately, this package may not work well for your use case. It is primarily designed for continued selection and changing the value as various things change in state is pivotal to its design. From what I understand you may be able to use the last selected color instead (I assume closing the picker onChange) but if that does not work for your UI you may need to seek a different package.
