### ISSUE TITLE
Module not found: Can't resolve 'uuid'

### ISSUE THREAD

**Issue by luckyadogun** [hxf31891/react-gradient-color-picker#49]
This happens after installation.

"next": "12.1.6",
"react": "18.1.0",

error - ./node_modules/react-best-gradient-color-picker/lib/components/Portal.js:9:0
Module not found: Can't resolve 'uuid'

Import trace for requested module:
./node_modules/react-best-gradient-color-picker/lib/components/EyeDropper.js
./node_modules/react-best-gradient-color-picker/lib/components/Controls.js
./node_modules/react-best-gradient-color-picker/lib/components/Picker.js
./node_modules/react-best-gradient-color-picker/lib/index.js
./pages/app/content-engine.js

https://nextjs.org/docs/messages/module-not-found

**Comment by hxf31891** [comment]
Will add to peer dependencies now, you can also install in your project. Thanks for pointing this out.

**Comment by hxf31891** [comment]
Fixed in v2.2.21
