### ISSUE TITLE
Possible to have gradients as presets?

### ISSUE THREAD

**Issue by simon-marcus** [hxf31891/react-gradient-color-picker#50]
Hi folks, I am able to set individual colors as presets, but I am unable to set _gradients_ as presets.
For example:
```js
const presetColors =
['#000000', '#F5222D', '#FA8C16', '#FADB14', '#8BBB11', '#52C41A', '#13A8A8'];

const presetGradients =
[
  'linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(250,219,20,1) 100%)',
  'linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(139,187,17,1) 100%)',
  'linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(82,196,26,1) 100%)',
  'linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(19,168,168,1) 100%)',
  'linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(22,119,255,1) 100%)',
  'linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(47,84,235,1) 100%)',
]

<ColorPicker presets={presetColors} /> // works great
<ColorPicker presets={presetGradients} /> //loads and displays preview but then errors on click

```
<img width="386" alt="image" src="https://github.com/hxf31891/react-gradient-color-picker/assets/16433553/6d982171-d353-448b-84ad-6a00f5a132ec">

<img width="1087" alt="image" src="https://github.com/hxf31891/react-gradient-color-picker/assets/16433553/e99d3636-16e3-404d-9a7d-35e108203733">

Any ideas?

**Comment by hxf31891** [comment]
@simon-marcus this was part of my initial features plan but somehow got left out. Will push an update soon.

**Comment by hxf31891** [comment]
See v2.2.21 which add ability to use gradients as presets.

Closing but please let me know if you have any issues.

**Comment by simon-marcus** [comment]
Nailed it! Thanks so much 🙏 
<img width="354" alt="image" src="https://github.com/hxf31891/react-gradient-color-picker/assets/16433553/d332941a-765f-4a3a-a8a8-9560e9d6aeea">
