### ISSUE TITLE
Is is possible to be more granular with what's disabled e.g. radial gradient?

### ISSUE THREAD

**Issue by ezekielaquino** [hxf31891/react-gradient-color-picker#51]
it would be great to be able to hide options more granularly e.g. I am enabling gradients, but only linear, without angles etc.

**Comment by hxf31891** [comment]
@ezekielaquino I'll add some more customization when I get a chance.

**Comment by hxf31891** [comment]
See v2.2.21 which adds

hideGradientType - hides linear/circular toggle
hideGradientAngle - hides linear angle input
hideGradientStop - hides gradient point stop input
hideGradientControls - hides entire gradient specific toolbar

Closing, but please reopen if you have any issue or need additional features!
