### ISSUE TITLE
cannot hide top bar of controls

### ISSUE THREAD

**Issue by chasedavis** [hxf31891/react-gradient-color-picker#52]
just found this library and loving it!

one nice enhancement would be to not render the top bar of the controls when it's contents are empty, and appropriately shift the layout

<img width="865" alt="Screen Shot 2023-07-16 at 3 52 31 PM" src="https://github.com/hxf31891/react-gradient-color-picker/assets/10068755/55848675-7769-416a-b858-d635f1bec57c">

**Comment by hxf31891** [comment]
Yea I noticed this the other day when I was adding some controls, easy fix.

**Comment by chasedavis** [comment]
Awesome quick fix thanks @hxf31891
