### ISSUE TITLE
Suggestion to remove `value` existence check from the hook `useColorPicker`

### ISSUE THREAD

**Issue by av-k** [hxf31891/react-gradient-color-picker#56]
Greetings!
First of all, thank you for this awesome library!

In conditions where I use the library, there is a possibility that a `value` doesn't exist or just doesn't need it.
Therefore, I have just a little suggestion to simplify the logic of the hook [useColorPicker](https://github.com/hxf31891/react-gradient-color-picker/blob/main/src/hooks/useColorPicker.js#L11) and remove the check (and remove `console.log`).
Business logic can be different, and saying in an imperative approach that you must provide a value is not the optimal case for everyone.

**Comment by hxf31891** [comment]
@av-k I can see how this would be annoying lol. I'll take it out, it really doesn't do much anyways.

**Comment by hxf31891** [comment]
@av-k fixed in 2.22.23
