### ISSUE TITLE
Missing Module Declaration + Cursor not moving to color position

### ISSUE THREAD

**Issue by PhillipSwann-main** [hxf31891/react-gradient-color-picker#57]
Hey! Your color picker looks amazing and it'd suit my page really well, but after importing it, I got error 
![image](https://github.com/hxf31891/react-gradient-color-picker/assets/37219827/5424b645-f116-49ae-8591-96ebe81c359d)
, then I turned off strict mode and declared it in 
![image](https://github.com/hxf31891/react-gradient-color-picker/assets/37219827/b5647c05-9196-491a-9d53-5dce9be82797)
.d.ts file, so import works now, but the cursor is not moving, here in this gif you can see the problem
![2023-08-22_13-01-03](https://github.com/hxf31891/react-gradient-color-picker/assets/37219827/6be70ace-9726-4c4c-8b5d-71879651117a)

React and DOM ver.: 18.2.0,
Tsx, Next.js

**Comment by hxf31891** [comment]
@PhillipSwann-main apologies for the slow response. Types have been added and in my testing the cursor is working. Please comment here if you experience otherwise.
