### ISSUE TITLE
Wrong alpha value computation

### ISSUE THREAD

**Issue by michalpalenkar** [hxf31891/react-gradient-color-picker#59]
When trying to set alpha value starting with 7 (e.g. 75), input will convert it into decimal number.

<img width="406" alt="color-picker-bug" src="https://github.com/hxf31891/react-gradient-color-picker/assets/30630540/98c34942-368d-4b7a-8758-826384cf4fb3">

Behavior is visible in the demo picker.

**Comment by hxf31891** [comment]
@michalpalenkar fixed in 2.22.23
