### ISSUE TITLE
After adding a new gradient point with click and hold, it is not possible to slide while holding.

### ISSUE THREAD

**Issue by pawelkontek** [hxf31891/react-gradient-color-picker#6]
After adding a new gradient point with click and hold, it is not possible to slide while holding.

**Comment by hxf31891** [comment]
Interesting, I haven't seen that bug yet. I think I know the cause though, should have a quick fix.

**Comment by pawelkontek** [comment]
@hxf31891 the issue is still present on 2.1.13
