### ISSUE TITLE
Emply div with height and padding

### ISSUE THREAD

**Issue by WKL10086** [hxf31891/react-gradient-color-picker#61]
<img width="814" alt="image" src="https://github.com/hxf31891/react-gradient-color-picker/assets/62619565/9aca376e-8990-4f9e-b474-abf8dbd059fb">

Problem: 
There are empty div as the above image shown when hideEyeDrop, hideAdvancedSliders, hideColorGuide, hideInputType, hideColorTypeBtns are selected.

Expect: 
The div would disappear ("display: none").

**Comment by hxf31891** [comment]
fixed in 2.2.24

**Comment by hxf31891** [comment]
Fixed in 2.2.24
