### ISSUE TITLE
Support HEXA

### ISSUE THREAD

**Issue by fstarlike** [hxf31891/react-gradient-color-picker#62]
Hi.

It's important that this tool supports the HEXA color values. Please add this feature ASAP.

Best.

**Comment by hxf31891** [comment]
@fstarlike I cant find any information on that color format. Can please attach some documentation here.

**Comment by JoniRinta-Kahila** [comment]
@fstarlike seems to be referring to the alpha channel, which can be used to determine the opacity of a color.

For example, blue color without Alpha channel:
```#0000FF``` [Blue color preview](https://webtools.fineaty.com/ColorInfo/0000FF/en/Information-about-the-0000FF-color.html)

And with Alpha:
```#0000FF80``` [Blue color preview with opacity](https://webtools.fineaty.com/ColorInfo/0000FF80/en/Information-about-the-0000FF80-color.html)

**Comment by hxf31891** [comment]
@fstarlike @JoniRinta-Kahila as of v3.0.14 there is a new prop added called "showHexAlpha"

Passing this into the picker as `true` will add the alpha channel to the value displayed in the HEX input.

Please let me know if you experience any issues or have additional enhancement requests!
