### ISSUE TITLE
Custom locales not working?

### ISSUE THREAD

**Issue by rmmssn** [hxf31891/react-gradient-color-picker#64]
Following the README instructions to pass a customLocales object to the locales prop doesn't seem to have any effect.

**Comment by hxf31891** [comment]
@rmmssn I'll look into it now, thats a new feature with the latest release and may have been merged incorrectly. What version do you have?

**Comment by rmmssn** [comment]
2.2.24

**Comment by hxf31891** [comment]
@rmmssn fixed in 2.2.25
