### ISSUE TITLE
Gradient Controls disappear

### ISSUE THREAD

**Issue by WKL10086** [hxf31891/react-gradient-color-picker#65]
<img width="214" alt="image" src="https://github.com/hxf31891/react-gradient-color-picker/assets/62619565/d099daa5-46b3-45a0-a4b5-fc557c0d272e">

Problem:
This issue is related to #61. Now the gradient controls would also disappear when hideEyeDrop, hideAdvancedSliders, hideColorGuide, hideInputType, hideColorTypeBtns are selected.

Expect:
![image](https://github.com/hxf31891/react-gradient-color-picker/assets/62619565/e0d0f3c7-164a-4acc-a941-cc6a88f04513)
The gradient controls still exist.

**Comment by WKL10086** [comment]
The version is bump from 2.2.22 to 2.2.24

**Comment by hxf31891** [comment]
@WKL10086 sorry about this, oversight on my part. Fixed in 2.2.25
