### ISSUE TITLE
Cant able to Coustomize labels like HEX ,RGB?

### ISSUE THREAD

**Issue by Support-Biztecno** [hxf31891/react-gradient-color-picker#68]
like we cant able to customize the labels that we are used like Hex , RGB, like if i want it above the input or below or Customize its styling like putting it bold etc

**Comment by hxf31891** [comment]
@Support-Biztecno additional style options are on the roadmap

**Comment by hxf31891** [comment]
@Support-Biztecno starting with v2.3.1 you can customize the input label by targeting the class "rbgcp-input-label"

for example add to your style sheet 
.rbgcp-input-label {
   font-weight: 800;
   color: pink
}
