### ISSUE TITLE
Can not select other points?

### ISSUE THREAD

**Issue by zerosoul** [hxf31891/react-gradient-color-picker#70]
This is what I want! Great work, thanks!
Code as document demo, but can not select other point, I don't know why.

![image](https://github.com/hxf31891/react-gradient-color-picker/assets/2985895/a53f679f-b456-4475-b590-316916232121)

[My demo](https://sinqi.tools/pattern/wave)

**Comment by hxf31891** [comment]
@zerosoul I am looking at your demo now and selecting points fine. Maybe its browser specific? Could you please comment with your machine, browser etc.

**Comment by hxf31891** [comment]
@zerosoul sorry for the delay. Are you still seeing this behavior?

**Comment by hxf31891** [comment]
Closing as stale
