### ISSUE TITLE
Latest version breaks when building inside a next project due to Global CSS cannot be imported from withing node_modules

### ISSUE THREAD

**Issue by samcodes-io** [hxf31891/react-gradient-color-picker#72]
Here is the error:

./node_modules/react-best-gradient-color-picker/lib/styles.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-best-gradient-color-picker/lib/index.js

**Comment by hxf31891** [comment]
@samcodes-io bummer! I was afraid this might happen but I tested on a next project and it seemed to work. Can you provide some info on next version, and the file your importing the component into please?

**Comment by hxf31891** [comment]
This should be fixed with v2.3.3 but I wasn't able to reproduce. @samcodes-io please confirm.

**Comment by av-k** [comment]
I noticed the same issue when versions **2.3.1**  and  **2.3.2** were released, but now in **2.3.3** everything works as before.

**Comment by hxf31891** [comment]
@av-k just confirming, when you say works as before you mean it works right? lol

**Comment by samcodes-io** [comment]
i will try next latest with react-gradient-color-picker latest and get back to you

**Comment by hxf31891** [comment]
@samcodes-io @av-k Thanks guys!
