### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by vptagupa** [hxf31891/react-gradient-color-picker#74]
Hi, I got this error in production and it is working in dev mode.

![image](https://github.com/hxf31891/react-gradient-color-picker/assets/8359629/8bd85961-6bbd-40e9-9894-7157fc67848c)

![image](https://github.com/hxf31891/react-gradient-color-picker/assets/8359629/e1099f9a-251f-41a6-8bfc-b4c791fc94ca)

**Comment by ilie-relik** [comment]
Same here

**Comment by ilie-relik** [comment]
@vptagupa if you use Vite as me, add it to vite.config.ts as I did.
<img width="510" alt="image" src="https://github.com/hxf31891/react-gradient-color-picker/assets/150026018/d379ac17-6bd1-40d2-b430-c1b08f769568">

**Comment by hxf31891** [comment]
It sounds like this is a resolved, thats for working together on it. I will add to the docs for future vite users.
