### ISSUE TITLE
Why is https://prod-api.outsyde.app/packagestyles.css used

### ISSUE THREAD

**Issue by NderimPlanA** [hxf31891/react-gradient-color-picker#75]
Hi, thanks for creating this package.

I wanted to ask, is there any reason you are using https://prod-api.outsyde.app/packagestyles.css? Seems to be from a company that is not related at all to development? 

I think this was added 2 weeks ago by @hxf31891

**Comment by hxf31891** [comment]
Hey @NderimPlanA great question.

Next compatibility with node module projects css files had been giving me fits. That domain belongs to another little side project of mine (feel free to check it out on the app store 😂) and I deployed the styles there as a work around. Now that I write this it makes a lot more sense to bundle them with the demo project and I will update there in the next version. Other than being un-usual does this create an issue for you?
