### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by vetalgo** [hxf31891/react-gradient-color-picker#79]
> ./node_modules/react-best-gradient-color-picker/dist/esm/hooks/useColorPicker.js 17:27
> Module parse failed: Unexpected token (17:27)
> File was processed with these loaders:
>  * ./node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
> |   //   )
> |   // }
>     const isGradient = value?.includes('gradient');
> |   const gradientType = getGradientType(value);
> |   const degrees = getDegrees(value);

**Comment by hxf31891** [comment]
@vetalgo investigating now

**Comment by hxf31891** [comment]
@vetalgo I believe this bug is fixed in v3.0.3 but I cant say for sure without knowing more about your environment.

If you get a second please update the package and lmk the result.

Thanks!

**Comment by hxf31891** [comment]
I believe this bug is now fixed as v3.0.3

Anyone who experiences the behaviour please reopen.
