### ISSUE TITLE
Next.js support

### ISSUE THREAD

**Issue by elie222** [hxf31891/react-gradient-color-picker#8]
The package doesn't support Next.js at this time due to this error:
https://nextjs.org/docs/messages/css-npm

```
./node_modules/react-best-gradient-color-picker/lib/styles.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-best-gradient-color-picker/lib/index.js
```

The fix would be to allow users to import the css themselves and not do it for them automatically.

**Comment by hxf31891** [comment]
Interesting, I was just thinking about using this in a next project. Thanks for pointing this out, I'll put something together.

**Comment by hxf31891** [comment]
Hi @RubenSmn and @elie222.

I just published a draft release https://github.com/hxf31891/react-gradient-color-picker/releases/tag/beta that I believe will fix the css import/Next compiling issue.

If either of you have a few minutes to confirm compatibility with Next and identify any bugs introduced by the switch to inline-js styles I would be greatly appreciative.

harry

**Comment by elie222** [comment]
Wasn't able to get it working. Didn't have time to debug.

`Module not found: Can't resolve 'react-best-gradient-color-picker'`

This is how I added it in package.json `"react-best-gradient-color-picker": "github:hxf31891/react-gradient-color-picker#beta"`, and then:

```ts
import GradientColorPicker from 'react-best-gradient-color-picker';

  const [color, setColor] = useState('rgba(255,255,255,1)');

  return <GradientColorPicker value={color} onChange={setColor} />
```

<img width="703" alt="image" src="https://user-images.githubusercontent.com/3090527/187074475-96117b6a-ccd1-41c8-8978-8c01624c5176.png">

**Comment by RubenSmn** [comment]
Me neither, got the same error as @elie222

**Comment by hxf31891** [comment]
Yup I'm just noticing there was a runtime error when I published the release. Will update ASAP.

**Comment by hxf31891** [comment]
@RubenSmn @elie222 Apologies for the delay, I just released v2.0.13 which removes all CSS imports in exchange for inline JS styling.

Its my understanding that this will fix your Next compiling issue. Shoot me a comment here to confirm when you can.

**Comment by RubenSmn** [comment]
Had some trouble importing the `ColorPicker`
Installed the most recent version `"react-best-gradient-color-picker": "^2.0.16"`

The code I used:
`import ColorPicker from 'react-best-gradient-color-picker';`

![Screenshot from 2022-09-04 12-27-31](https://user-images.githubusercontent.com/31519867/188308980-f298e2aa-5884-4396-9b62-031fe726c377.png)

**Comment by jourdanrodrigues** [comment]
I also get the same error as @RubenSmn but within the Jest environment. This might be related to/solved by #14.

**Comment by jourdanrodrigues** [comment]
Adding `@babel/preset-env` on Babel config solved it on my side. Will push a test setup shortly that will include this change.

**Comment by hxf31891** [comment]
@jourdanrodrigues's changes are available with 2.0.17. Hopefully this works for the Next crew as well.

**Comment by RubenSmn** [comment]
@hxf31891 it got fixed for the `react-best-gradient-color-picker`! But now got the same import error for the `react-color-eye-dropper`

**Comment by jourdanrodrigues** [comment]
@hxf31891 How do you feel about merging this `react-color-eye-dropper` into this one? Seems small enough to me and Babel preset should handle it properly.

**Comment by hxf31891** [comment]
@jourdanrodrigues I think thats a great idea, I can't remember why I split it off in the first place.

**Comment by RubenSmn** [comment]
Got it working for my Nextjs project, thanks everyone!

**Comment by hxf31891** [comment]
@elie222 @RubenSmn glad y'all got it working. I just pushed an update (2.1.3) that I tested on Next (12.3). This version should run well if you guys are still having any issues.
