### ISSUE TITLE
the color bar is not updating in version 3

### ISSUE THREAD

**Issue by penobit** [hxf31891/react-gradient-color-picker#81]
hi there!
i was using version 2 of this package, and everythin was fine.

Now in the version 3 there is a problem! the color bar is not getting updated.
Let's say i have a rect with gradient color starts from white and ends with black. now when i click on the last stop (black) the color picker bar still is on the white and doesn't get updated automatically!

as you can see in this screenshot the current color is blue but the color picker is on blue!
![image](https://github.com/hxf31891/react-gradient-color-picker/assets/60283818/9e27760e-d652-4142-b078-a5a2d1c4c72b)

**Comment by penobit** [comment]
you can see it in your own live preview:
https://gradient-package-demo.web.app/

**Comment by hxf31891** [comment]
@penobit wow good find, thank you. Patching now

**Comment by hxf31891** [comment]
@penobit fixed in v3.0.3

Please comment if behavior continues.

**Comment by hxf31891** [comment]
@penobit  fixed in v3.0.3

Please comment if behavior continues.
