### ISSUE TITLE
Conflicting overflow styles causing incorrect scrolling behavior

### ISSUE THREAD

**Issue by JoniRinta-Kahila** [hxf31891/react-gradient-color-picker#82]
**Description:**
Firstly, I would like to express my gratitude for the excellent library.
However, I am currently facing an issue with the react-gradient-color-picker@3.0.5 library in conjunction with the @headlessui/react@1.7.17 dialog. The problem arises when the ColorPicker sets document.body.style.overflow to 'auto', and subsequently, the @headlessui/react dialog component adds overflow: hidden to the HTML tag when the dialog opens. This conflicting behavior is causing the site to scroll to the top erroneously.

**Reproduction:**
1. Add the react-gradient-color-picker@3.0.5 library into the project.
2. Use the library's functionalities on the site.
3. Observe that the body's overflow is set to 'auto'.
4. Open a @headlessui/react@1.7.17 dialog, which adds "overflow: hidden" to the HTML tag when the dialog opens.
5. Notice that the site scrolls to the top unexpectedly.

Is changing the body style completely necessary for this library?

**Comment by hxf31891** [comment]
No it's not necessary at all, in fact I am not even sure how it made it in there. Will push a fix asap.

**Comment by hxf31891** [comment]
@JoniRinta-Kahila can you please confirm that this is fixed after your recent PR?

**Comment by JoniRinta-Kahila** [comment]
Thank you. Problem fixed.
