### ISSUE TITLE
Component is loading in an external stylesheet

### ISSUE THREAD

**Issue by ezekielaquino** [hxf31891/react-gradient-color-picker#83]
The component seems to be pulling in a stylesheet externally which can be included in the package. Also, the external style is not accessible anyway

<img width="528" alt="image" src="https://github.com/hxf31891/react-gradient-color-picker/assets/4451733/e8a22089-ba12-409e-9e2e-04c11eaaea0d">

**Comment by hxf31891** [comment]
Update to v3.0.5
