### ISSUE TITLE
Support RGB colors with alpha

### ISSUE THREAD

**Issue by jourdanrodrigues** [hxf31891/react-gradient-color-picker#9]
This is the pattern: `rgb(<r> <g> <b> / <a>)`.

I tried tweaking the `tokens` comma but it didn't work.

**Comment by hxf31891** [comment]
Can you elaborate? It supports RGBA with rgba( r, g, b, a)

**Comment by jourdanrodrigues** [comment]
@hxf31891 The pattern I mentioned (`rgb(<r> <g> <b> / <a>)`) will be used for cross-platform communication. The same value will get sent to web, Android and iOS to put together a view based on this.

We chose that pattern for colors because parsing the pieces with the comma pattern (`rgba(<r>, <g>, <b>, <a>)`) in a gradient string is very hard to maintain and slow, even if not using regexes, which are slow by default.

**Comment by hxf31891** [comment]
Merged in v2.0.13
