### ISSUE TITLE
All classes in components are "undefined"

### ISSUE THREAD

**Issue by mattparlane** [hxf31891/react-gradient-color-picker#97]
Sorry to create an issue since I'm not sure this is reproducible, and it's pretty vague...

I had to convert my project to esm (`"type": "module"` in `package.json`), and after this all `class` attributes in the color picker are `undefined`:

![Screenshot 2024-06-13 194552](https://github.com/hxf31891/react-gradient-color-picker/assets/176572/cc4bb28e-855f-4be4-b3f3-c6ee60ff70eb)

I have tried to look through the source code to figure out what's going on, but I can't even see where the class names should be coming from.

For example if I search for a random class name (like `rbgcpColorModelDropdown`), it only exists in the stylesheet, and then it's referred to in JS, it's never defined in JS:

https://github.com/search?q=repo%3Ahxf31891%2Freact-gradient-color-picker%20rbgcpColorModelDropdown&type=code

Is something parsing the stylesheet and creating the class names? What is going on?

I'm using 3.0.8 btw.

Happy to provide more information, please let me know where I should be looking. Thanks!

**Comment by hxf31891** [comment]
Likely related to [issue 100](https://github.com/hxf31891/react-gradient-color-picker/issues/100).

Can you give me some info on your env?

**Comment by hxf31891** [comment]
@mattparlane this should be fixed as of 3.0.10
