### ISSUE TITLE
Unable to select `0` as a stop position.

### ISSUE THREAD

**Issue by M-J-Robbins** [hxf31891/react-gradient-color-picker#99]
Hiya, 
I'm loving this tool and I think I've found a small bug. Initially I thought this was something I had done but i also realised that it appears on the [demo site](https://gradient-package-demo.web.app/) too.

When dragging the stop position in the selector, I'm unable to drag it down to `0`, the lowest available value seems to be `1`. On the other end i can go up to `100` without issue.

This is also an issue when typing in a value if I type `0` is doesn't register, but other values are fine. So I'm guessing it's some kind of validation going on that sets the range from `1` to `100` rather than `0` to `100`.
<img width="360" alt="image" src="https://github.com/hxf31891/react-gradient-color-picker/assets/7871206/a694e9b6-fb96-4bdd-a77b-ca504591c90c">

**Comment by hxf31891** [comment]
@M-J-Robbins Interesting I haven't seen this one yet. Will try and patch ASAP.

**Comment by hxf31891** [comment]
@M-J-Robbins this should be fixed as of 3.0.10
